supported_languages = {
    'es': 'Spanish',
    'ar': 'Arabic',
    'fr': 'French',
    'zh-cn': 'Chinese (Simplified)',
    'zh-tw': 'Chinese (Traditional)',
    'hi': 'Hindi',
    'ja': 'Japanese',
    'ko': 'Korean',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'vi': 'Vietnamese',
    'de': 'German',
    'it': 'Italian',
    'id': 'Indonesian',
    'ms': 'Malay',
    'th': 'Thai',
    'tr': 'Turkish',
    'pl': 'Polish',
    'nl': 'Dutch',
    'hu': 'Hungarian',
    'cs': 'Czech',
    'el': 'Greek',
    'fi': 'Finnish'
}
