name: aiwave
version: 0.0.1+1
description: Embark on a transformative data exploration journey with our cutting-edge Flutter application, inspired by the powerful AiWave repository.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # UI and Animation:
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  curved_navigation_bar: ^1.0.3
  flutter_otp_text_field: ^1.1.1
  shimmer: ^3.0.0
  awesome_snackbar_content: ^0.1.3
  carousel_slider: ^4.0.0
  flutter_slidable: ^3.0.0
  circular_menu: ^2.0.1
  simple_ripple_animation: ^0.0.7
  animated_theme_switcher: ^2.0.8
  animated_text_kit: ^4.2.2
  drop_down_list: ^0.0.6
  multi_select_flutter: ^4.1.3

  # Image and Media:
  cached_network_image: ^3.2.3
  image_picker: ^1.0.1
  multiple_images_picker: ^1.0.1
  file_picker: ^6.1.1
  flutter_svg: ^2.0.7
  lottie: ^3.0.0
  video_player: ^2.8.1
  chewie: ^1.7.1

  # State Management and Data Handling:
  get: ^4.6.5
  get_storage: ^2.1.1

  # Utilities and Helpers:
  permission_handler: ^11.1.0
  intl: ^0.18.0
  uuid: ^4.2.2

  # UI Input and Forms:
  font_awesome_flutter: ^10.5.0
  flutter_rating_bar: ^4.0.1
  scrollable_positioned_list: ^0.3.8
  dropdown_button2: ^2.3.9
  speech_to_text: ^6.5.1
  markdown_widget: ^2.3.2+3

  # Other Dependencies:
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.12

  # Wave local dependencies
  wave_core:
    path: ./packages/wave_core

  wave_auth:
    path: ./packages/wave_auth

  wave_storage:
    path: ./packages/wave_storage

  wave_ai:
    path: ./packages/wave_ai

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
